language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
matrix:
  allow_failures:
    - env: TOXENV=py34  # No support on Travis CI at this time; remove later
  fast_finish: true
install:
  - travis_retry pip install coveralls tox==1.6.1
script:
  - travis_retry tox
after_success:
  - coveralls
