language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script: 
  - coverage run -m nose
after_success:
  - coveralls
